name: Deploy to WordPress.org
on:
  push:
    tags:
      - "*"
jobs:
  tag:
    name: New tag
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Build
        run: |
          npm install
          composer install
          npm run build
      - name: Get tag version
        run: echo ::set-env name=RELEASE_VERSION::$(echo ${GITHUB_REF:10})
      - name: Change plugin version
        run: ./bin/create-release.sh ${{ env.RELEASE_VERSION }}
      - name: Update README.md from readme.txt
        run: npx grunt
      - name: Push readme.txt etc to GitHub
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name "naogify"
          git config --global user.email "n.globe.us@gmail.com"
          git remote set-url origin https://naogify:${GITHUB_TOKEN}@github.com/naogify/wp-simple-spreadsheet-fetcher-for-google.git
          git checkout -b master
          git add .
          git commit -m"Update Version"
          git push origin master
      # - name: WordPress Plugin Deploy
      #   uses: 10up/action-wordpress-plugin-deploy@master
      #   env:
      #     SVN_PASSWORD: ${{ secrets.SVN_PASSWORD }}
      #     SVN_USERNAME: ${{ secrets.SVN_USERNAME }}
